### DISCUSSION TITLE
GitHub Merge Queue Support

### DISCUSSION THREAD

**Discussion by brand-it** [qltysh/qlty#1203] [Feature Requests]
### Problem statement

The problem comes with your trying to use github merge queues, and you want to make the `fmt` check required. Because github does not let you bypass rules, you have this weird problem where you can use merge queue and qlt checks. A workaround a lot of people have done for other tools is to create a github action that pushes a status of passed with the same name as the status that is reported by the tool.

![Screenshot 2024-11-21 at 11 36 01 AM](https://github.com/user-attachments/assets/fa65f062-f58c-4bd2-9a00-d0c9469292ae)

### Solution brainstorm (optional)

A hack that I have used before is to place a github action that does nothing but has the same name as the check-in question so it reports as passed.

```yaml
name: fmt

on:
  push:
    branches:
      - 'gh-readonly-queue*'

jobs:
  fmt-check:
    name: fmt
    runs-on: ubuntu-latest

    steps:
      - name: Report FMT Status
        run: echo "FMT check always passes."
```

I have no idea if this system works, but it worked with code fresh/code coverage checks, so why not work here?

**Comment by brand-it** [comment]
Updated Solution/workaround needed to be more accurate.

Create a new workflow like this and ensure the required check is from any source. Merge queue will let it pass. 

```yaml

name: QLTY Fmt

on:
  merge_group:
    types: [checks_requested]

jobs:
  fmt-check:
    name: fmt
    runs-on: ubuntu-latest

    steps:
      - name: Report FMT Status
        run: echo "FMT check always passes."
```

![Screenshot 2024-11-22 at 11 04 05 AM](https://github.com/user-attachments/assets/1c02907a-d728-4dcb-9312-8a09a7d5b70e)
