### DISCUSSION TITLE
I'm getting a "not a terminal" error and it's not clear how to proceed

### DISCUSSION THREAD

**Discussion by asdkant-bf** [qltysh/qlty#1252] [Q&A] [answered]
### Question

I'm trying out qlty in the context of a pipeline (Azure pipelines), but when I run `qlty init` I get this output:
```
› Initializing qlty in the current directory...
✔ Created .qlty/ directory
✔ Fetched plugins definitions
✔ Created .gitignore in .qlty/
✔ Created qlty.toml config file with 7 plugins

Plugin         Version  Targets    Config
prettier       latest   8 files    
markdownlint   0.41.0   1 files    
yamllint       latest   1 files    
trivy          latest   3 files    
trufflehog     latest   135 files  
golangci-lint  latest   0 files    
checkov        latest   9 files    

✔ Set up qlty in the current directory
❌ IO error: not a terminal

Caused by:
    not a terminal

```

Am I not supposed to run this outside of an interactive terminal? the documentation is not really clearon that point.

### How to reproduce (optional)

the YAML code for my pipeline:
```yaml
steps:
- bash: |
    curl https://qlty.sh | bash
  displayName: instal qlty
- bash: |
    source /home/vsts/.config/.bashrc
    # it breaks here
    qlty init
  displayName: qlty init
- bash: |
    source /home/vsts/.config/.bashrc
    qlty metrics --all --max-depth=2 --sort complexity --limit 10
  displayName: qlty metrics
```

### CLI Version

0.458.0 (d0c76b8)

### Information about Qlty configuration and environment (optional)

- OS: ubuntu (ubuntu-latest runner from Azure Pipelines)
