### ISSUE TITLE
Bug: Coverage files aren't being uploaded correctly

### ISSUE THREAD

**Issue by tim-gq** [qltysh/qlty#1267]
### What happened?

It looks like my ~3-4MB of combined coverage files aren't being uploaded correctly.  Publish output finishes with `Uploaded 924 B in 0.88s!`.  No coverage info shows on the pull requests or the Qlty dashboard.  In the dashboard, I do see the "upload commit" listed, but there are no files showing if I click into it.

@brynary has a copy of the coverage files if they're helpful for debugging.

This is the from the Github Actions log:

```
/usr/bin/tar x --warning=no-unknown-keyword --overwrite -C /home/runner/work/_temp/<snip> -f /home/runner/work/_temp/<snip>
/opt/hostedtoolcache/qlty/latest/x64/qlty-x86_64-unknown-linux-gnu/qlty coverage publish /tmp/coverage-0/partial-coverage.json /tmp/coverage-1/partial-coverage.json /tmp/coverage-10/partial-coverage.json /tmp/coverage-11/partial-coverage.json /tmp/coverage-2/partial-coverage.json /tmp/coverage-3/partial-coverage.json /tmp/coverage-4/partial-coverage.json /tmp/coverage-5/partial-coverage.json /tmp/coverage-6/partial-coverage.json /tmp/coverage-7/partial-coverage.json /tmp/coverage-8/partial-coverage.json /tmp/coverage-9/partial-coverage.json /tmp/coverage-rspec/partial-coverage.json
qlty 0.460.0 

  Retrieving CI metadata...
  → GitHub CI commit "e[16]<snip> on branch "main"

  Reading code coverage data...
  → Found 13 files with code coverage data

  Authenticating with Qlty...
  Exporting code coverage data...
  → Exported to "tmp/qlty-coverage"

  → Using coverage token "***"

  Uploading coverage data...
  → Uploaded 9[24](<snip>) B in 0.88s!
```

This is the relevant part of our github actions config:
```
      - name: Find coverage files
        id: find_coverage_files
        run: |
          files=$(find /tmp/coverage-* -name partial-coverage.json | tr '\n' ' ')
          echo "coverage_files=$files" >> $GITHUB_OUTPUT

      - name: Upload total coverage to Qlty
        uses: qltysh/qlty-action/coverage@main
        with:
          coverage-token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: ${{ steps.find_coverage_files.outputs.coverage_files }}

```

### What did you expect to happen?

Coverage stats to be shown in the dashboard and on the PR.

### Can you reproduce the problem?

Yes, consistently

### CLI Version

qltysh/qlty-action/coverage@main

### Relevant log output

```shell

```
