### ISSUE TITLE
Bug: unexpected character 'v' while parsing major version number

### ISSUE THREAD

**Issue by lamualfa** [qltysh/qlty#1280]
## Reproduction

1. `curl https://qlty.sh | sh`
2. `qlty init`
3. `qlty check --all`

And I got this error:

```bash
[0/1] 🤔  Planning...  ❌ unexpected character 'v' while parsing major version number
```

## Relevant Files

**`.qlty/qlty.toml`**

```toml
# This file was automatically generated by `qlty init`.
# You can modify it to suit your needs.
# We recommend you to commit this file to your repository.
#
# This configuration is used by both Qlty CLI and Qlty Cloud.
#
#     Qlty CLI -- Code quality toolkit for developers
#     Qlty Cloud -- Fully automated Code Health Platform
#
# Try Qlty Cloud: https://qlty.sh
#
# For a guide to configuration, visit https://qlty.sh/d/config
# Or for a full reference, visit https://qlty.sh/d/qlty-toml
config_version = "0"

exclude_patterns = [
  "*_min.*",
  "*-min.*",
  "*.min.*",
  "**/*.d.ts",
  "**/.yarn/**",
  "**/bower_components/**",
  "**/build/**",
  "**/cache/**",
  "**/config/**",
  "**/db/**",
  "**/deps/**",
  "**/dist/**",
  "**/extern/**",
  "**/external/**",
  "**/generated/**",
  "**/Godeps/**",
  "**/gradlew/**",
  "**/mvnw/**",
  "**/node_modules/**",
  "**/protos/**",
  "**/seed/**",
  "**/target/**",
  "**/testdata/**",
  "**/vendor/**",
  "**/assets/**",
]

test_patterns = [
  "**/test/**",
  "**/spec/**",
  "**/*.test.*",
  "**/*.spec.*",
  "**/*_test.*",
  "**/*_spec.*",
  "**/test_*.*",
  "**/spec_*.*",
]

[[source]]
name = "default"
repository = "https://github.com/qltysh/qlty.git"
tag = "v0.460.0"


[[plugin]]
name = "actionlint"

[[plugin]]
name = "biome"
version = "1.8.3"

[[plugin]]
name = "brakeman"

[[plugin]]
name = "checkov"

[[plugin]]
name = "dotenv-linter"

[[plugin]]
name = "eslint"
version = "v4.19.1"
package_file = "package.json"
package_filters = ["eslint"]

[[plugin]]
name = "golangci-lint"

[[plugin]]
name = "markdownlint"
version = "0.41.0"

[[plugin]]
name = "osv-scanner"

[[plugin]]
name = "prettier"

[[plugin]]
name = "ripgrep"

[[plugin]]
name = "shellcheck"

[[plugin]]
name = "shfmt"

[[plugin]]
name = "trivy"
drivers = [
  "fs-vuln",
  "config",
]

[[plugin]]
name = "trufflehog"

[[plugin]]
name = "yamllint"
```

**`package.json`**

```json
{
  "name": "redacted",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "postinstall": "lefthook install",
    "dev": "next dev --turbopack --port $(env-cmd node -e \"process.stdout.write(process.env.APP_PORT)\")",
    "dev:pws": "for /F %i in ('env-cmd node -e \"process.stdout.write(process.env.APP_PORT)\"') do next dev --turbopack --port %i",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@mantine/core": "^7.14.1",
    "@mantine/hooks": "^7.14.1",
    "@prisma/client": "6.0.0",
    "@tabler/icons-react": "^3.22.0",
    "ai": "^4.0.6",
    "better-auth": "0.8.9-beta.2",
    "clsx": "^2.1.1",
    "midtrans-client": "^1.4.2",
    "next": "15.0.4-canary.33",
    "ollama-ai-provider": "^1.0.0",
    "react": "19.0.0-rc-66855b96-20241106",
    "react-dom": "19.0.0-rc-66855b96-20241106",
    "react-markdown": "^9.0.1",
    "react-syntax-highlighter": "^15.6.1",
    "rehype-katex": "^7.0.1",
    "remark-gfm": "^4.0.0",
    "remark-math": "^6.0.0",
    "valibot": "1.0.0-beta.8"
  },
  "devDependencies": {
    "@biomejs/biome": "1.9.4",
    "@commitlint/cli": "^19.6.0",
    "@commitlint/config-conventional": "^19.6.0",
    "@devoss/tailwind-plugin-mantine": "^2.1.0",
    "@tailwindcss/typography": "^0.5.15",
    "@types/node": "^20.17.6",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "@types/react-syntax-highlighter": "^15.5.13",
    "env-cmd": "^10.1.0",
    "eslint": "^8",
    "eslint-config-next": "15.0.3",
    "lefthook": "^1.8.4",
    "postcss": "^8.4.49",
    "postcss-preset-mantine": "^1.17.0",
    "postcss-simple-vars": "^7.0.1",
    "prisma": "^6.0.0",
    "tailwind-scrollbar": "^3.1.0",
    "tailwindcss": "^3.4.1",
    "tailwindcss-debug-screens": "^2.2.1",
    "tsx": "^4.19.2",
    "typescript": "^5"
  },
  "packageManager": "pnpm@9.12.3+sha512.cce0f9de9c5a7c95bef944169cc5dfe8741abfb145078c0d508b868056848a87c81e626246cb60967cbd7fd29a6c062ef73ff840d96b3c86c40ac92cf4a813ee"
}
```

### What did you expect to happen?

To works properly.

### Can you reproduce the problem?

Yes, consistently

### CLI Version

qlty 0.460.0 (41527f4)

### Relevant log output

```shell

```

**Comment by brynary** [comment]
Hello @lamualfa -- Thank you for this bug report. This bug has been fixed in `main` and will be in the next release.

The `qlty init` command generated a bad configuration for you.

Specifically this section:

```toml
[[plugin]]
name = "eslint"
version = "v4.19.1" # This is the problematic line
package_file = "package.json"
package_filters = ["eslint"]
```

Should be like this:

```toml
[[plugin]]
name = "eslint"
version = "8.57.0" # Note: No leading "v" and a version in the v8 family
package_file = "package.json"
package_filters = ["eslint"]
```

Sorry for the trouble and please let us know if you have any additional issues. Thanks.
