### ISSUE TITLE
Bug: Parse error biome: EOF while parsing a value at line 1 column 0

### ISSUE THREAD

**Issue by lamualfa** [qltysh/qlty#1282]
## Reproduction

1. `curl https://qlty.sh | sh`
2. `qlty init`
3. `qlty check --all`

And I got this error:

```bash
     [0/1] 🤔  Planning...  0.02s
     [1/1] 🔍  Analyzing all targets... 
Parse error biome: EOF while parsing a value at line 1 column 0 .qlty/out/invocations/invoke-IgT1pt.yaml

Checked 34 files
❌ Lint error
```

## Relevant Files

**`biome.json`**

```json
{
  "$schema": "https://biomejs.dev/schemas/1.9.4/schema.json",
  "vcs": {
    "enabled": true,
    "clientKind": "git",
    "useIgnoreFile": true,
    "defaultBranch": "production"
  },
  "files": {
    "ignoreUnknown": true,
    "ignore": []
  },
  "formatter": {
    "enabled": true,
    "indentStyle": "space",
    "formatWithErrors": true
  },
  "organizeImports": {
    "enabled": true
  },
  "linter": {
    "enabled": true,
    "ignore": ["midtrans-client.d.ts"],
    "rules": {
      "recommended": true,
      "correctness": {
        "noUnusedVariables": "error",
        "noNodejsModules": "error",
        "noUnusedFunctionParameters": "error",
        "noUnusedImports": "error"
      },
      "complexity": {
        "noForEach": "error",
        "useSimplifiedLogicExpression": "error"
      },
      "style": {
        "noNegationElse": "error",
        "useConsistentBuiltinInstantiation": "error",
        "useCollapsedElseIf": "error",
        "useExplicitLengthCheck": "error",
        "useFilenamingConvention": {
          "level": "error",
          "options": {
            "filenameCases": ["kebab-case"]
          }
        }
      },
      "nursery": {
        "noDescendingSpecificity": "error",
        "useGuardForIn": "error",
        "useConsistentCurlyBraces": "error",
        "useSortedClasses": {
          "level": "error",
          "fix": "safe",
          "options": {
            "functions": ["clsx", "tw"]
          }
        }
      }
    }
  },
  "javascript": {
    "formatter": {
      "quoteStyle": "double",
      "semicolons": "asNeeded"
    }
  },
  "css": {
    "parser": {
      "cssModules": true
    }
  }
}
```

**`.qlty/out/invocations/invoke-IgT1pt.yaml`**

```yaml
id: IgT1pt
qltyCliVersion: 0.460.0
pluginName: biome
driverName: lint
pluginVersion: 1.8.3
verb: EXECUTION_VERB_CHECK
targetsCount: 34
targetPaths:
- src/app/[[...chat]]/mocks/chat-history.ts
- src/libs/config.ts
- src/app/api/chat/route.ts
- .eslintrc.json
- src/enum/e-ai-models.ts
- src/app/[[...chat]]/components/sidebar/utils/index.ts
- src/app/[[...chat]]/components/main-chat/index.ts
- src/app/[[...chat]]/components/main-chat/components/chat-header/components/index.ts
- tailwind.config.ts
- .vscode/settings.json
- .vscode/extensions.json
- src/app/[[...chat]]/types.ts
- src/app/[[...chat]]/components/main-chat/components/chat-section/components/index.ts
- src/app/ui/popup/components/index.ts
- src/libs/db.ts
- biome.json
- next.config.ts
- postcss.config.mjs
- src/app/[[...chat]]/mocks/ai-models.ts
- src/app/[[...chat]]/components/sidebar/index.ts
- src/app/[[...chat]]/components/main-chat/components/chat-header/index.ts
- src/app/api/auth/[...all]/route.ts
- src/libs/auth.ts
- tsconfig.json
- commitlint.config.mjs
- src/app/[[...chat]]/components/index.ts
- src/app/[[...chat]]/components/sidebar/components/index.ts
- src/app/[[...chat]]/components/main-chat/components/index.ts
- src/app/[[...chat]]/components/main-chat/components/chat-section/index.ts
- src/libs/payment.ts
- src/app/[[...chat]]/components/sidebar/utils/group-history-by-date.ts
- src/app/theme.ts
- package.json
- src/libs/ai.ts
configPaths:
- /home/laode/Repositories/redacted/biome.json
script: sh -c "biome lint --reporter=json 'src/app/[[...chat]]/mocks/chat-history.ts' src/libs/config.ts src/app/api/chat/route.ts .eslintrc.json src/enum/e-ai-models.ts 'src/app/[[...chat]]/components/sidebar/utils/index.ts' 'src/app/[[...chat]]/components/main-chat/index.ts' 'src/app/[[...chat]]/components/main-chat/components/chat-header/components/index.ts' tailwind.config.ts .vscode/settings.json .vscode/extensions.json 'src/app/[[...chat]]/types.ts' 'src/app/[[...chat]]/components/main-chat/components/chat-section/components/index.ts' src/app/ui/popup/components/index.ts src/libs/db.ts biome.json next.config.ts postcss.config.mjs 'src/app/[[...chat]]/mocks/ai-models.ts' 'src/app/[[...chat]]/components/sidebar/index.ts' 'src/app/[[...chat]]/components/main-chat/components/chat-header/index.ts' 'src/app/api/auth/[...all]/route.ts' src/libs/auth.ts tsconfig.json commitlint.config.mjs 'src/app/[[...chat]]/components/index.ts' 'src/app/[[...chat]]/components/sidebar/components/index.ts' 'src/app/[[...chat]]/components/main-chat/components/index.ts' 'src/app/[[...chat]]/components/main-chat/components/chat-section/index.ts' src/libs/payment.ts 'src/app/[[...chat]]/components/sidebar/utils/group-history-by-date.ts' src/app/theme.ts package.json src/libs/ai.ts"
cwd: /home/laode/Repositories/redacted/
env:
  NODE_PATH: /home/laode/.qlty/cache/tools/biome/1.8.3-f7399a70c713/node_modules
  PATH: /home/laode/.qlty/cache/tools/biome/1.8.3-f7399a70c713/node_modules/.bin:/home/laode/.qlty/cache/tools/node/21.7.3-3f206cb4295e/bin:/home/laode/.qlty/cache/tools/node/21.7.3-3f206cb4295e:/home/laode/.qlty/cache/tools/node/21.7.3-3f206cb4295e/bin:/home/laode/.qlty/cache/tools/node/21.7.3-3f206cb4295e:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
  HOME: /home/laode
startedAt: 2024-12-09T16:33:31.282640538+00:00
durationSecs: 0.03167196
exitCode: '1'
stderr: "/home/laode/Repositories/redacted/biome.json:29:9 deserialize ━━━━━━━━━━━━━━━━━━━━━━━━\n\n  × Found an unknown key `noUnusedFunctionParameters`.\n  \n    27 │         \"noUnusedVariables\": \"error\",\n    28 │         \"noNodejsModules\": \"error\",\n  > 29 │         \"noUnusedFunctionParameters\": \"error\",\n       │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    30 │         \"noUnusedImports\": \"error\"\n    31 │       },\n  \n  i Known keys:\n  \n  - recommended\n  - all\n  - noChildrenProp\n  - noConstAssign\n  - noConstantCondition\n  - noConstantMathMinMaxClamp\n  - noConstructorReturn\n  - noEmptyCharacterClassInRegex\n  - noEmptyPattern\n  - noFlatMapIdentity\n  - noGlobalObjectCalls\n  - noInnerDeclarations\n  - noInvalidConstructorSuper\n  - noInvalidNewBuiltin\n  - noInvalidUseBeforeDeclaration\n  - noNewSymbol\n  - noNodejsModules\n  - noNonoctalDecimalEscape\n  - noPrecisionLoss\n  - noRenderReturnValue\n  - noSelfAssign\n  - noSetterReturn\n  - noStringCaseMismatch\n  - noSwitchDeclarations\n  - noUndeclaredVariables\n  - noUnnecessaryContinue\n  - noUnreachable\n  - noUnreachableSuper\n  - noUnsafeFinally\n  - noUnsafeOptionalChaining\n  - noUnusedImports\n  - noUnusedLabels\n  - noUnusedPrivateClassMembers\n  - noUnusedVariables\n  - noVoidElementsWithChildren\n  - noVoidTypeReturn\n  - useArrayLiterals\n  - useExhaustiveDependencies\n  - useHookAtTopLevel\n  - useIsNan\n  - useJsxKeyInIterable\n  - useValidForDirection\n  - useYield\n  \n\n/home/laode/Repositories/redacted/biome.json:38:9 deserialize ━━━━━━━━━━━━━━━━━━━━━━━━\n\n  × Found an unknown key `useConsistentBuiltinInstantiation`.\n  \n    36 │       \"style\": {\n    37 │         \"noNegationElse\": \"error\",\n  > 38 │         \"useConsistentBuiltinInstantiation\": \"error\",\n       │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    39 │         \"useCollapsedElseIf\": \"error\",\n    40 │         \"useExplicitLengthCheck\": \"error\",\n  \n  i Known keys:\n  \n  - recommended\n  - all\n  - noArguments\n  - noCommaOperator\n  - noDefaultExport\n  - noImplicitBoolean\n  - noInferrableTypes\n  - noNamespace\n  - noNamespaceImport\n  - noNegationElse\n  - noNonNullAssertion\n  - noParameterAssign\n  - noParameterProperties\n  - noRestrictedGlobals\n  - noShoutyConstants\n  - noUnusedTemplateLiteral\n  - noUselessElse\n  - noVar\n  - useAsConstAssertion\n  - useBlockStatements\n  - useCollapsedElseIf\n  - useConsistentArrayType\n  - useConst\n  - useDefaultParameterLast\n  - useEnumInitializers\n  - useExponentiationOperator\n  - useExportType\n  - useFilenamingConvention\n  - useForOf\n  - useFragmentSyntax\n  - useImportType\n  - useLiteralEnumMembers\n  - useNamingConvention\n  - useNodeAssertStrict\n  - useNodejsImportProtocol\n  - useNumberNamespace\n  - useNumericLiterals\n  - useSelfClosingElements\n  - useShorthandArrayType\n  - useShorthandAssign\n  - useShorthandFunctionType\n  - useSingleCaseStatement\n  - useSingleVarDeclarator\n  - useTemplate\n  - useWhile\n  \n\n/home/laode/Repositories/redacted/biome.json:40:9 deserialize ━━━━━━━━━━━━━━━━━━━━━━━━\n\n  × Found an unknown key `useExplicitLengthCheck`.\n  \n    38 │         \"useConsistentBuiltinInstantiation\": \"error\",\n    39 │         \"useCollapsedElseIf\": \"error\",\n  > 40 │         \"useExplicitLengthCheck\": \"error\",\n       │         ^^^^^^^^^^^^^^^^^^^^^^^^\n    41 │         \"useFilenamingConvention\": {\n    42 │           \"level\": \"error\",\n  \n  i Known keys:\n  \n  - recommended\n  - all\n  - noArguments\n  - noCommaOperator\n  - noDefaultExport\n  - noImplicitBoolean\n  - noInferrableTypes\n  - noNamespace\n  - noNamespaceImport\n  - noNegationElse\n  - noNonNullAssertion\n  - noParameterAssign\n  - noParameterProperties\n  - noRestrictedGlobals\n  - noShoutyConstants\n  - noUnusedTemplateLiteral\n  - noUselessElse\n  - noVar\n  - useAsConstAssertion\n  - useBlockStatements\n  - useCollapsedElseIf\n  - useConsistentArrayType\n  - useConst\n  - useDefaultParameterLast\n  - useEnumInitializers\n  - useExponentiationOperator\n  - useExportType\n  - useFilenamingConvention\n  - useForOf\n  - useFragmentSyntax\n  - useImportType\n  - useLiteralEnumMembers\n  - useNamingConvention\n  - useNodeAssertStrict\n  - useNodejsImportProtocol\n  - useNumberNamespace\n  - useNumericLiterals\n  - useSelfClosingElements\n  - useShorthandArrayType\n  - useShorthandAssign\n  - useShorthandFunctionType\n  - useSingleCaseStatement\n  - useSingleVarDeclarator\n  - useTemplate\n  - useWhile\n  \n\n/home/laode/Repositories/redacted/biome.json:49:9 deserialize ━━━━━━━━━━━━━━━━━━━━━━━━\n\n  × Found an unknown key `noDescendingSpecificity`.\n  \n    47 │       },\n    48 │       \"nursery\": {\n  > 49 │         \"noDescendingSpecificity\": \"error\",\n       │         ^^^^^^^^^^^^^^^^^^^^^^^^^\n    50 │         \"useGuardForIn\": \"error\",\n    51 │         \"useConsistentCurlyBraces\": \"error\",\n  \n  i Known keys:\n  \n  - recommended\n  - all\n  - noConsole\n  - noDoneCallback\n  - noDuplicateAtImportRules\n  - noDuplicateElseIf\n  - noDuplicateFontNames\n  - noDuplicateJsonKeys\n  - noDuplicateSelectorsKeyframeBlock\n  - noEmptyBlock\n  - noEvolvingTypes\n  - noExportedImports\n  - noImportantInKeyframe\n  - noInvalidDirectionInLinearGradient\n  - noInvalidPositionAtImportRule\n  - noLabelWithoutControl\n  - noMisplacedAssertion\n  - noReactSpecificProps\n  - noRestrictedImports\n  - noShorthandPropertyOverrides\n  - noSubstr\n  - noUndeclaredDependencies\n  - noUnknownFunction\n  - noUnknownMediaFeatureName\n  - noUnknownProperty\n  - noUnknownPseudoClassSelector\n  - noUnknownSelectorPseudoElement\n  - noUnknownUnit\n  - noUnmatchableAnbSelector\n  - noUnusedFunctionParameters\n  - noUselessStringConcat\n  - noUselessUndefinedInitialization\n  - noYodaExpression\n  - useAdjacentOverloadSignatures\n  - useConsistentBuiltinInstantiation\n  - useConsistentGridAreas\n  - useDateNow\n  - useDefaultSwitchClause\n  - useDeprecatedReason\n  - useErrorMessage\n  - useExplicitLengthCheck\n  - useFocusableInteractive\n  - useGenericFontNames\n  - useImportExtensions\n  - useImportRestrictions\n  - useNumberToFixedDigitsArgument\n  - useSemanticElements\n  - useSortedClasses\n  - useThrowNewError\n  - useThrowOnlyError\n  - useTopLevelRegex\n  - useValidAutocomplete\n  \n\n/home/laode/Repositories/redacted/biome.json:50:9 deserialize ━━━━━━━━━━━━━━━━━━━━━━━━\n\n  × Found an unknown key `useGuardForIn`.\n  \n    48 │       \"nursery\": {\n    49 │         \"noDescendingSpecificity\": \"error\",\n  > 50 │         \"useGuardForIn\": \"error\",\n       │         ^^^^^^^^^^^^^^^\n    51 │         \"useConsistentCurlyBraces\": \"error\",\n    52 │         \"useSortedClasses\": {\n  \n  i Known keys:\n  \n  - recommended\n  - all\n  - noConsole\n  - noDoneCallback\n  - noDuplicateAtImportRules\n  - noDuplicateElseIf\n  - noDuplicateFontNames\n  - noDuplicateJsonKeys\n  - noDuplicateSelectorsKeyframeBlock\n  - noEmptyBlock\n  - noEvolvingTypes\n  - noExportedImports\n  - noImportantInKeyframe\n  - noInvalidDirectionInLinearGradient\n  - noInvalidPositionAtImportRule\n  - noLabelWithoutControl\n  - noMisplacedAssertion\n  - noReactSpecificProps\n  - noRestrictedImports\n  - noShorthandPropertyOverrides\n  - noSubstr\n  - noUndeclaredDependencies\n  - noUnknownFunction\n  - noUnknownMediaFeatureName\n  - noUnknownProperty\n  - noUnknownPseudoClassSelector\n  - noUnknownSelectorPseudoElement\n  - noUnknownUnit\n  - noUnmatchableAnbSelector\n  - noUnusedFunctionParameters\n  - noUselessStringConcat\n  - noUselessUndefinedInitialization\n  - noYodaExpression\n  - useAdjacentOverloadSignatures\n  - useConsistentBuiltinInstantiation\n  - useConsistentGridAreas\n  - useDateNow\n  - useDefaultSwitchClause\n  - useDeprecatedReason\n  - useErrorMessage\n  - useExplicitLengthCheck\n  - useFocusableInteractive\n  - useGenericFontNames\n  - useImportExtensions\n  - useImportRestrictions\n  - useNumberToFixedDigitsArgument\n  - useSemanticElements\n  - useSortedClasses\n  - useThrowNewError\n  - useThrowOnlyError\n  - useTopLevelRegex\n  - useValidAutocomplete\n  \n\n/home/laode/Repositories/redacted/biome.json:51:9 deserialize ━━━━━━━━━━━━━━━━━━━━━━━━\n\n  × Found an unknown key `useConsistentCurlyBraces`.\n  \n    49 │         \"noDescendingSpecificity\": \"error\",\n    50 │         \"useGuardForIn\": \"error\",\n  > 51 │         \"useConsistentCurlyBraces\": \"error\",\n       │         ^^^^^^^^^^^^^^^^^^^^^^^^^^\n    52 │         \"useSortedClasses\": {\n    53 │           \"level\": \"error\",\n  \n  i Known keys:\n  \n  - recommended\n  - all\n  - noConsole\n  - noDoneCallback\n  - noDuplicateAtImportRules\n  - noDuplicateElseIf\n  - noDuplicateFontNames\n  - noDuplicateJsonKeys\n  - noDuplicateSelectorsKeyframeBlock\n  - noEmptyBlock\n  - noEvolvingTypes\n  - noExportedImports\n  - noImportantInKeyframe\n  - noInvalidDirectionInLinearGradient\n  - noInvalidPositionAtImportRule\n  - noLabelWithoutControl\n  - noMisplacedAssertion\n  - noReactSpecificProps\n  - noRestrictedImports\n  - noShorthandPropertyOverrides\n  - noSubstr\n  - noUndeclaredDependencies\n  - noUnknownFunction\n  - noUnknownMediaFeatureName\n  - noUnknownProperty\n  - noUnknownPseudoClassSelector\n  - noUnknownSelectorPseudoElement\n  - noUnknownUnit\n  - noUnmatchableAnbSelector\n  - noUnusedFunctionParameters\n  - noUselessStringConcat\n  - noUselessUndefinedInitialization\n  - noYodaExpression\n  - useAdjacentOverloadSignatures\n  - useConsistentBuiltinInstantiation\n  - useConsistentGridAreas\n  - useDateNow\n  - useDefaultSwitchClause\n  - useDeprecatedReason\n  - useErrorMessage\n  - useExplicitLengthCheck\n  - useFocusableInteractive\n  - useGenericFontNames\n  - useImportExtensions\n  - useImportRestrictions\n  - useNumberToFixedDigitsArgument\n  - useSemanticElements\n  - useSortedClasses\n  - useThrowNewError\n  - useThrowOnlyError\n  - useTopLevelRegex\n  - useValidAutocomplete\n  \n\nconfiguration ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n  × Biome exited because the configuration resulted in errors. Please fix them.\n  \n\n"
exitResult: EXIT_RESULT_SUCCESS
parserError: EOF while parsing a value at line 1 column 0
```

**`.qlty/qlty.toml`**

```toml
# This file was automatically generated by `qlty init`.
# You can modify it to suit your needs.
# We recommend you to commit this file to your repository.
#
# This configuration is used by both Qlty CLI and Qlty Cloud.
#
#     Qlty CLI -- Code quality toolkit for developers
#     Qlty Cloud -- Fully automated Code Health Platform
#
# Try Qlty Cloud: https://qlty.sh
#
# For a guide to configuration, visit https://qlty.sh/d/config
# Or for a full reference, visit https://qlty.sh/d/qlty-toml
config_version = "0"

exclude_patterns = [
  "*_min.*",
  "*-min.*",
  "*.min.*",
  "**/*.d.ts",
  "**/.yarn/**",
  "**/bower_components/**",
  "**/build/**",
  "**/cache/**",
  "**/config/**",
  "**/db/**",
  "**/deps/**",
  "**/dist/**",
  "**/extern/**",
  "**/external/**",
  "**/generated/**",
  "**/Godeps/**",
  "**/gradlew/**",
  "**/mvnw/**",
  "**/node_modules/**",
  "**/protos/**",
  "**/seed/**",
  "**/target/**",
  "**/testdata/**",
  "**/vendor/**",
  "**/assets/**",
]

test_patterns = [
  "**/test/**",
  "**/spec/**",
  "**/*.test.*",
  "**/*.spec.*",
  "**/*_test.*",
  "**/*_spec.*",
  "**/test_*.*",
  "**/spec_*.*",
]

[[source]]
name = "default"
repository = "https://github.com/qltysh/qlty.git"
tag = "v0.460.0"


# [[plugin]]
# name = "actionlint"

[[plugin]]
name = "biome"
version = "1.8.3"

# [[plugin]]
# name = "brakeman"

# [[plugin]]
# name = "checkov"

# [[plugin]]
# name = "dotenv-linter"

# [[plugin]]
# name = "eslint"
# version = "4.19.1"
# package_file = "package.json"
# package_filters = ["eslint"]

# [[plugin]]
# name = "golangci-lint"

# [[plugin]]
# name = "markdownlint"
# version = "0.41.0"

# [[plugin]]
# name = "osv-scanner"

# [[plugin]]
# name = "prettier"

# [[plugin]]
# name = "ripgrep"

# [[plugin]]
# name = "shellcheck"

# [[plugin]]
# name = "shfmt"

# [[plugin]]
# name = "trivy"
# drivers = [
#   "fs-vuln",
#   "config",
# ]

# [[plugin]]
# name = "trufflehog"

# [[plugin]]
# name = "yamllint"
```

**`package.json`**

```json
{
  "name": "redacted",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "postinstall": "lefthook install",
    "dev": "next dev --turbopack --port $(env-cmd node -e \"process.stdout.write(process.env.APP_PORT)\")",
    "dev:pws": "for /F %i in ('env-cmd node -e \"process.stdout.write(process.env.APP_PORT)\"') do next dev --turbopack --port %i",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@mantine/core": "^7.14.1",
    "@mantine/hooks": "^7.14.1",
    "@prisma/client": "6.0.0",
    "@tabler/icons-react": "^3.22.0",
    "ai": "^4.0.6",
    "better-auth": "0.8.9-beta.2",
    "clsx": "^2.1.1",
    "midtrans-client": "^1.4.2",
    "next": "15.0.4-canary.33",
    "ollama-ai-provider": "^1.0.0",
    "react": "19.0.0-rc-66855b96-20241106",
    "react-dom": "19.0.0-rc-66855b96-20241106",
    "react-markdown": "^9.0.1",
    "react-syntax-highlighter": "^15.6.1",
    "rehype-katex": "^7.0.1",
    "remark-gfm": "^4.0.0",
    "remark-math": "^6.0.0",
    "valibot": "1.0.0-beta.8"
  },
  "devDependencies": {
    "@biomejs/biome": "1.9.4",
    "@commitlint/cli": "^19.6.0",
    "@commitlint/config-conventional": "^19.6.0",
    "@devoss/tailwind-plugin-mantine": "^2.1.0",
    "@tailwindcss/typography": "^0.5.15",
    "@types/node": "^20.17.6",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "@types/react-syntax-highlighter": "^15.5.13",
    "env-cmd": "^10.1.0",
    "eslint": "^8",
    "eslint-config-next": "15.0.3",
    "lefthook": "^1.8.4",
    "postcss": "^8.4.49",
    "postcss-preset-mantine": "^1.17.0",
    "postcss-simple-vars": "^7.0.1",
    "prisma": "^6.0.0",
    "tailwind-scrollbar": "^3.1.0",
    "tailwindcss": "^3.4.1",
    "tailwindcss-debug-screens": "^2.2.1",
    "tsx": "^4.19.2",
    "typescript": "^5"
  },
  "packageManager": "pnpm@9.12.3+sha512.cce0f9de9c5a7c95bef944169cc5dfe8741abfb145078c0d508b868056848a87c81e626246cb60967cbd7fd29a6c062ef73ff840d96b3c86c40ac92cf4a813ee"
}
```

### What did you expect to happen?

To works properly.

### Can you reproduce the problem?

Yes, consistently

### CLI Version

qlty 0.460.0 (41527f4)

**Comment by lamualfa** [comment]
Fixed after updating the qlty biome plugin version to the correct version in `package.json`:

```toml
[[plugin]]
name = "biome"
version = "1.8.3"
```
