### ISSUE TITLE
Bug: `qlty smells -a` didn't fail the lefthook when there's an issue

### ISSUE THREAD

**Issue by lamualfa** [qltysh/qlty#1290]
## Questions

- Is `qlty smells -a` meant to fail if something goes wrong like `qlty check -a` does?
- If no, what the best practice to use `qlty smells -a`?
- Is it possible to fix inconsistent color output between lefthook & direct terminal execution?

**Output when running through lefthook**

![Image](https://github.com/user-attachments/assets/b7006980-f0b6-4a9d-8616-9b0c7571a804)

**Output when running directly in terminal**

![Image](https://github.com/user-attachments/assets/76e1f99a-edfe-4a6a-bb7f-8df8e6689f28)

## Relevant Files

**`lefthook.yml`**

```yml
pre-commit:
  commands:
    check:
      run: qlty check -a
      stage_fixed: true
    smells:
      run: qlty smells -a
      stage_fixed: true
commit-msg:
  commands:
    lint:
      run: pnpm exec commitlint -e
```

**`.qlty/qlty.toml`**

```toml
# This file was automatically generated by `qlty init`.
# You can modify it to suit your needs.
# We recommend you to commit this file to your repository.
#
# This configuration is used by both Qlty CLI and Qlty Cloud.
#
#     Qlty CLI -- Code quality toolkit for developers
#     Qlty Cloud -- Fully automated Code Health Platform
#
# Try Qlty Cloud: https://qlty.sh
#
# For a guide to configuration, visit https://qlty.sh/d/config
# Or for a full reference, visit https://qlty.sh/d/qlty-toml
config_version = "0"

exclude_patterns = [
  "*_min.*",
  "*-min.*",
  "*.min.*",
  "**/*.d.ts",
  "**/.yarn/**",
  "**/bower_components/**",
  "**/build/**",
  "**/cache/**",
  "**/config/**",
  "**/db/**",
  "**/deps/**",
  "**/dist/**",
  "**/extern/**",
  "**/external/**",
  "**/generated/**",
  "**/Godeps/**",
  "**/gradlew/**",
  "**/mvnw/**",
  "**/node_modules/**",
  "**/protos/**",
  "**/seed/**",
  "**/target/**",
  "**/testdata/**",
  "**/vendor/**",
  "**/assets/**",
  "**/pnpm-lock.yaml"
]

test_patterns = [
  "**/test/**",
  "**/spec/**",
  "**/*.test.*",
  "**/*.spec.*",
  "**/*_test.*",
  "**/*_spec.*",
  "**/test_*.*",
  "**/spec_*.*",
]

[[source]]
name = "default"
default = true

[[plugin]]
name = "actionlint"

[[plugin]]
name = "biome"
version = "1.9.4"

[[plugin]]
name = "checkov"

[[plugin]]
name = "dotenv-linter"

[[plugin]]
name = "eslint"
version = "8.57.0"
package_file = "package.json"
package_filters = ["eslint"]

[[plugin]]
name = "osv-scanner"

[[plugin]]
name = "trivy"
drivers = [
  "config",
  "fs-vuln",
]

[[plugin]]
name = "trufflehog"

[[plugin]]
name = "yamllint"
```

### What did you expect to happen?

If there's an issue on the code, `qlty smells -a` should be fail.

### Can you reproduce the problem?

Yes, consistently

### CLI Version

qlty 0.462.0 linux-x64 (4eb973a/4eb973a 2024-12-09)

### Relevant log output

```shell

```
