### ISSUE TITLE
Bug: Eslint 9 support

### ISSUE THREAD

**Issue by lamualfa** [qltysh/qlty#1542]
**Command**

```bash
qlty check --no-upgrade-check
```

**Error**

```bash
 ERRORS: 1 

Plugin  Result                                               Message                      Debug File
eslint  Error                                                Exited with code 2 in 0.13s  .qlty/out/invoke-evTf5K.yaml
        Value for 'config' of type 'path::String' required.  You're using eslint.config.js, some command line flags are no longer available. Please see https://eslint.org/docs/latest/use/command-line-interface for details.
❌ Lint error
```

**`.qlty/out/invoke-evTf5K.yaml`**

```yaml
id: evTf5K
qltyCliVersion: 0.497.0
pluginName: eslint
driverName: lint
pluginVersion: 9.21.0
verb: EXECUTION_VERB_CHECK
targetsCount: 5
targetPaths:
- src/libs/const.ts
- src/app/page.tsx
- src/components/header/nav.tsx
- src/app/page.client.tsx
- src/components/header.tsx
script: sh -c "eslint --config  --output-file /tmp/invocation-out-evTf5K.txt --format json src/libs/const.ts src/app/page.tsx src/components/header/nav.tsx src/app/page.client.tsx src/components/header.tsx"
cwd: /<REDACTED>/<REDACTED>/
env:
  PATH: /<REDACTED>/.qlty/cache/tools/eslint/9.21.0-c1fd83c18928/node_modules/.bin:/<REDACTED>/.qlty/cache/tools/node/21.7.3-3f206cb4295e/bin:/<REDACTED>/.qlty/cache/tools/node/21.7.3-3f206cb4295e:/<REDACTED>/.qlty/cache/tools/node/21.7.3-3f206cb4295e/bin:/<REDACTED>/.qlty/cache/tools/node/21.7.3-3f206cb4295e:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
  HOME: /<REDACTED>
  NODE_PATH: /<REDACTED>/.qlty/cache/tools/eslint/9.21.0-c1fd83c18928/node_modules
startedAt: <REDACTED>
durationSecs: 0.1328111
exitCode: '2'
stderr: |
  Value for 'config' of type 'path::String' required.
  You're using eslint.config.js, some command line flags are no longer available. Please see https://eslint.org/docs/latest/use/command-line-interface for details.
tmpfilePath: /tmp/invocation-out-evTf5K.txt
exitResult: EXIT_RESULT_KNOWN_ERROR
```

**`.eslintrc.json`**
```json
{
  "extends": ["next/core-web-vitals", "next/typescript"]
}
```

**`package.json`**

```json
{
  "name": "<REDACTED>",
  "version": "<REDACTED>",
  "private": true,
  "scripts": {
    "postinstall": "lefthook install",
    "dev": "next dev --turbopack",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "@mantine/core": "^7.17.1",
    "@mantine/hooks": "^7.17.1",
    "@popperjs/core": "^2.11.8",
    "add": "^2.0.6",
    "bootstrap": "^5.3.2",
    "clsx": "^2.1.1",
    "gsap": "^3.12.5",
    "imagesloaded": "^5.0.0",
    "isotope-layout": "^3.0.6",
    "next": "15.2.0",
    "react": "^19.0.0",
    "react-dom": "^19.0.0",
    "react-fast-marquee": "^1.6.3",
    "react-masonry-css": "^1.0.16",
    "react-modal-video": "^2.0.2",
    "react-scroll-parallax": "^3.4.5",
    "react-slick": "^0.30.3",
    "react-tooltip": "^5.26.0",
    "sass": "^1.71.1",
    "slick-carousel": "^1.8.1",
    "wowjs": "^1.1.3"
  },
  "devDependencies": {
    "@biomejs/biome": "1.9.4",
    "@commitlint/cli": "^19.7.1",
    "@commitlint/config-conventional": "^19.7.1",
    "@tailwindcss/postcss": "^4.0.0",
    "@types/node": "^22",
    "@types/react": "^19",
    "@types/react-dom": "^19",
    "@types/react-slick": "^0.23.13",
    "eslint": "^9.21.0",
    "eslint-config-next": "15.2.0",
    "lefthook": "^1.11.2",
    "postcss": "^8.4.49",
    "postcss-preset-mantine": "^1.17.0",
    "postcss-simple-vars": "^7.0.1",
    "tailwind-scrollbar": "^4.0.1",
    "tailwindcss": "^4.0.9",
    "typescript": "^5"
  },
  "packageManager": "pnpm@9.14.2+sha512.6e2baf77d06b9362294152c851c4f278ede37ab1eba3a55fda317a4a17b209f4dbb973fb250a77abc463a341fcb1f17f17cfa24091c4eb319cda0d9b84278387"
}
```

**`.qlty/qlty.toml`**

```toml
# This file was automatically generated by `qlty init`.
# You can modify it to suit your needs.
# We recommend you to commit this file to your repository.
#
# This configuration is used by both Qlty CLI and Qlty Cloud.
#
#     Qlty CLI -- Code quality toolkit for developers
#     Qlty Cloud -- Fully automated Code Health Platform
#
# Try Qlty Cloud: https://qlty.sh
#
# For a guide to configuration, visit https://qlty.sh/d/config
# Or for a full reference, visit https://qlty.sh/d/qlty-toml
config_version = "0"

exclude_patterns = [
  "*_min.*",
  "*-min.*",
  "*.min.*",
  "**/*.d.ts",
  "**/.yarn/**",
  "**/bower_components/**",
  "**/build/**",
  "**/cache/**",
  "**/config/**",
  "**/db/**",
  "**/deps/**",
  "**/dist/**",
  "**/extern/**",
  "**/external/**",
  "**/generated/**",
  "**/Godeps/**",
  "**/gradlew/**",
  "**/mvnw/**",
  "**/node_modules/**",
  "**/protos/**",
  "**/seed/**",
  "**/target/**",
  "**/testdata/**",
  "**/vendor/**",
  "**/assets/**",
]

test_patterns = [
  "**/test/**",
  "**/spec/**",
  "**/*.test.*",
  "**/*.spec.*",
  "**/*_test.*",
  "**/*_spec.*",
  "**/test_*.*",
  "**/spec_*.*",
]

[[source]]
name = "default"
default = true

[[plugin]]
name = "actionlint"

[[plugin]]
name = "biome"
version = "1.9.4"

[[plugin]]
name = "eslint"
version = "9.21.0"
package_file = "package.json"
package_filters = ["eslint"]

[[plugin]]
name = "osv-scanner"

[[plugin]]
name = "trufflehog"

[[plugin]]
name = "yamllint"

[[ignore]]
plugins = ["yamllint"]
rules = ["line-length", "truthy"]
file_patterns = ["pnpm-lock.yaml", "lefthook.yml"]
```

**What did you expect to happen?**

Eslint v9 support, v8 works well.

**CLI Version**

qlty 0.497.0 linux-x64 (9eae4b0 2025-02-28)
