### ISSUE TITLE
Bug: EOF while parsing a value at line 1 column 0 Rubocop

### ISSUE THREAD

**Issue by brand-it** [qltysh/qlty#1578]
### What happened?

`qlty check` fails to parse rubcop json

```yml
id: OVt3LZ
qltyCliVersion: 0.485.0
pluginName: rubocop
driverName: lint
pluginVersion: bundled
verb: EXECUTION_VERB_CHECK
targetsCount: 13
targetPaths:
- app/queries/searchkick/menu_items_query.rb
- spec/api/core/v202507/search_spec.rb
- app/models/lat_lon.rb
- app/models/listing_menu.rb
- spec/factories/menu_items.rb
- spec/queries/searchkick/menu_items_query_spec.rb
- spec/queries/bloomreach/menu_items_query_spec.rb
- app/api/core/v202507/search.rb
- spec/api/core/v202507/entities/search_spec.rb
- app/queries/bloomreach/menu_items_query.rb
- lib/bloomreach/relation.rb
- app/api/core/v202507/entities/search.rb
- spec/models/lat_lon_spec.rb
configPaths:
- /Users/brandit/apps/weedmaps/.rubocop_todo.yml
- /Users/brandit/apps/weedmaps/lib/weedmaps/linters/it_behaves_like.rb
- /Users/brandit/apps/weedmaps/.rubocop.yml
script: sh -c "rubocop --format json app/queries/searchkick/menu_items_query.rb spec/api/core/v202507/search_spec.rb app/models/lat_lon.rb app/models/listing_menu.rb spec/factories/menu_items.rb spec/queries/searchkick/menu_items_query_spec.rb spec/queries/bloomreach/menu_items_query_spec.rb app/api/core/v202507/search.rb spec/api/core/v202507/entities/search_spec.rb app/queries/bloomreach/menu_items_query.rb lib/bloomreach/relation.rb app/api/core/v202507/entities/search.rb spec/models/lat_lon_spec.rb"
cwd: /Users/brandit/apps/weedmaps/
env:
  HOME: /Users/brandit
  GEM_HOME: /Users/brandit/.qlty/cache/tools/rubocop/bundled-a5c45834bdf8
  BUNDLE_PATH: /Users/brandit/.qlty/cache/tools/rubocop/bundled-a5c45834bdf8
  PKG_CONFIG_PATH: /Users/brandit/.qlty/cache/tools/ruby/3.3.7-81c2a315940d/lib/pkgconfig
  BUNDLE_GEMFILE: /Users/brandit/.qlty/cache/tools/rubocop/bundled-a5c45834bdf8/Gemfile
  RUBYOPT: -rbundler/setup
  GEM_PATH: /Users/brandit/.qlty/cache/tools/rubocop/bundled-a5c45834bdf8
  PATH: /Users/brandit/.qlty/cache/tools/rubocop/bundled-a5c45834bdf8/ruby/3.3.0/bin:/Users/brandit/.qlty/cache/tools/ruby/3.3.7-81c2a315940d/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
  BUNDLE_JOBS: '4'
  RUBYLIB: /Users/brandit/.qlty/cache/tools/ruby/3.3.7-81c2a315940d/lib/ruby/site_ruby/3.3.0:/Users/brandit/.qlty/cache/tools/ruby/3.3.7-81c2a315940d/lib/ruby/site_ruby/3.3.0/arm64-darwin23:/Users/brandit/.qlty/cache/tools/ruby/3.3.7-81c2a315940d/lib/ruby/site_ruby:/Users/brandit/.qlty/cache/tools/ruby/3.3.7-81c2a315940d/lib/ruby/vendor_ruby/3.3.0:/Users/brandit/.qlty/cache/tools/ruby/3.3.7-81c2a315940d/lib/ruby/vendor_ruby/3.3.0/arm64-darwin23:/Users/brandit/.qlty/cache/tools/ruby/3.3.7-81c2a315940d/lib/ruby/vendor_ruby:/Users/brandit/.qlty/cache/tools/ruby/3.3.7-81c2a315940d/lib/ruby/3.3.0:/Users/brandit/.qlty/cache/tools/ruby/3.3.7-81c2a315940d/lib/ruby/3.3.0/arm64-darwin23:/Users/brandit/.qlty/cache/tools/ruby/3.3.7-81c2a315940d/lib/ruby/
  BUNDLE_RETRY: '3'
startedAt: 2025-03-25T21:19:03.997468+00:00
durationSecs: 0.57312965
exitCode: '1'
stderr: "/Users/brandit/.qlty/cache/tools/ruby/3.3.7-81c2a315940d/lib/ruby/3.3.0/bundled_gems.rb:69:in `require': superclass mismatch for class Prism::ParseResult (Object is given but was Prism::Result) (TypeError)\n\n        kernel_class.send(:no_warning_require, name)\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^\n\tfrom /Users/brandit/.qlty/cache/tools/ruby/3.3.7-81c2a315940d/lib/ruby/3.3.0/bundled_gems.rb:69:in `block (2 levels) in replace_require'\n\tfrom /Users/brandit/.qlty/cache/tools/ruby/3.3.7-81c2a315940d/lib/ruby/3.3.0/prism.rb:96:in `<top (required)>'\n\tfrom /Users/brandit/.qlty/cache/tools/ruby/3.3.7-81c2a315940d/lib/ruby/3.3.0/bundled_gems.rb:69:in `require'\n\tfrom /Users/brandit/.qlty/cache/tools/ruby/3.3.7-81c2a315940d/lib/ruby/3.3.0/bundled_gems.rb:69:in `block (2 levels) in replace_require'\n\tfrom /Users/brandit/.qlty/cache/tools/rubocop/bundled-a5c45834bdf8/ruby/3.3.0/gems/rubocop-ast-1.43.0/lib/rubocop/ast.rb:4:in `<top (required)>'\n\tfrom /Users/brandit/.qlty/cache/tools/rubocop/bundled-a5c45834bdf8/ruby/3.3.0/gems/rubocop-ast-1.43.0/lib/rubocop-ast.rb:3:in `require_relative'\n\tfrom /Users/brandit/.qlty/cache/tools/rubocop/bundled-a5c45834bdf8/ruby/3.3.0/gems/rubocop-ast-1.43.0/lib/rubocop-ast.rb:3:in `<top (required)>'\n\tfrom /Users/brandit/.qlty/cache/tools/ruby/3.3.7-81c2a315940d/lib/ruby/3.3.0/bundled_gems.rb:69:in `require'\n\tfrom /Users/brandit/.qlty/cache/tools/ruby/3.3.7-81c2a315940d/lib/ruby/3.3.0/bundled_gems.rb:69:in `block (2 levels) in replace_require'\n\tfrom /Users/brandit/.qlty/cache/tools/rubocop/bundled-a5c45834bdf8/ruby/3.3.0/gems/rubocop-1.69.2/lib/rubocop.rb:19:in `<top (required)>'\n\tfrom /Users/brandit/.qlty/cache/tools/ruby/3.3.7-81c2a315940d/lib/ruby/3.3.0/bundled_gems.rb:69:in `require'\n\tfrom /Users/brandit/.qlty/cache/tools/ruby/3.3.7-81c2a315940d/lib/ruby/3.3.0/bundled_gems.rb:69:in `block (2 levels) in replace_require'\n\tfrom /Users/brandit/.qlty/cache/tools/rubocop/bundled-a5c45834bdf8/ruby/3.3.0/gems/rubocop-1.69.2/exe/rubocop:14:in `<top (required)>'\n\tfrom /Users/brandit/.qlty/cache/tools/rubocop/bundled-a5c45834bdf8/ruby/3.3.0/bin/rubocop:25:in `load'\n\tfrom /Users/brandit/.qlty/cache/tools/rubocop/bundled-a5c45834bdf8/ruby/3.3.0/bin/rubocop:25:in `<main>'\n"
exitResult: EXIT_RESULT_SUCCESS
parserError: EOF while parsing a value at line 1 column 0
```

Json generated by rubocop.
```json
{"metadata":{"rubocop_version":"1.69.2","ruby_engine":"ruby","ruby_version":"3.3.1","ruby_patchlevel":"55","ruby_platform":"arm64-darwin23"},"files":[{"path":"app/queries/searchkick/menu_items_query.rb","offenses":[]},{"path":"spec/api/core/v202507/search_spec.rb","offenses":[]},{"path":"app/models/lat_lon.rb","offenses":[]},{"path":"app/models/listing_menu.rb","offenses":[]},{"path":"spec/factories/menu_items.rb","offenses":[]},{"path":"spec/queries/searchkick/menu_items_query_spec.rb","offenses":[]},{"path":"spec/queries/bloomreach/menu_items_query_spec.rb","offenses":[]},{"path":"app/api/core/v202507/search.rb","offenses":[]},{"path":"spec/api/core/v202507/entities/search_spec.rb","offenses":[]},{"path":"app/queries/bloomreach/menu_items_query.rb","offenses":[]},{"path":"lib/bloomreach/relation.rb","offenses":[]},{"path":"app/api/core/v202507/entities/search.rb","offenses":[]},{"path":"spec/models/lat_lon_spec.rb","offenses":[]}],"summary":{"offense_count":0,"target_file_count":13,"inspected_file_count":13}}
```

### What did you expect to happen?

Not a EOF error

### Can you reproduce the problem?

Yes, consistently

### CLI Version

0.485.0 & 0.500.0

### Relevant log output

```shell
https://qlty.sh/gh/GhostGroup/projects/weedmaps/builds/74301598-0d23-4fbd-9937-ea9bdc0a0d92
```
