### ISSUE TITLE
Bug: ghcr.io/qltysh/qlty integration nwith gitlab CI results in error: unrecognized subcommand 'sh'

### ISSUE THREAD

**Issue by patpatpat123** [qltysh/qlty#1627]
### What happened?

Hello team,

How are you?

Just wanted to reach out to report a bug when trying to integrate ghcr.io/qltysh/qlty with GitLab CI.

This is our gitlab configuration:

```
quality:
  script:
    - qlty check --sample=5
  image:
    name: ghcr.io/qltysh/qlty
  stage: quality
  artifacts:
    paths: [ gl-code-quality-report.json ]
    reports:
      codequality: gl-code-quality-report.json

```

By configuring this, we are expecting that at this CI job, the docker image ghcr.io/qltysh/qlty would be pulled, and start a scan on the code base, to finally produce a bug report file.

However, instead, we are faced with this error:

```
Using Docker executor with image ghcr.io/qltysh/qlty ...
Pulling docker image ghcr.io/qltysh/qlty ...
Using docker image sha256:3acc477696df6617e5984d398468c5a1f48fd47abbda48de2a72668e63a34c81 for ghcr.io/qltysh/qlty with digest ghcr.io/qltysh/qlty@sha256:8ea873335a56c577c693d0aa12df83fa443483de0bc8cd9835478a783694a1c5 ...

Using docker image sha256:3acc477696df6617e5984d398468c5a1f48fd47abbda48de2a72668e63a34c81 for ghcr.io/qltysh/qlty with digest ghcr.io/qltysh/qlty@sha256:8ea873335a56c577c693d0aa12df83fa443483de0bc8cd9835478a783694a1c5 ...
error: unrecognized subcommand 'sh'
  tip: a similar subcommand exists: 'dashboard'
Usage: qlty [OPTIONS] [COMMAND]
For more information, try '--help'.
```

Could you please help with this issue?

Thank you and good day!

### What did you expect to happen?

A successfull analysis of the code base with results report

### Can you reproduce the problem?

Yes, consistently

### CLI Version

ghcr.io/qltysh/qlty this should pull the latest

### Relevant log output

```shell

```
