### ISSUE TITLE
Update `qlty config migrate` to disable any plugins not found in `.codeclimate.yml`

### ISSUE THREAD

**Issue by brynary** [qltysh/qlty#2093]
## Context

When customers migrate projects from Code Climate Quality (Quality) to Qlty, their initial analysis results in Qlty are often perceived as "noisy." This happens because our `qlty init` command, which runs for projects without an existing `qlty.toml`, enables a broad set of new plugins by default.

Many of these plugins were not available or used in Quality, leading to customer confusion and a poor first experience with Qlty's analysis. While `qlty config migrate` currently handles `exclude_patterns` and adjusts maintainability thresholds, it doesn't limit the enabled plugins to those explicitly configured in the original `.codeclimate.yml`.

## Goal

Our goal is to ensure that when a project with an existing `.codeclimate.yml` is migrated to Qlty, the resulting `qlty.toml` configuration is as close as possible to the original `.codeclimate.yml` in terms of **enabled plugins**. This will significantly reduce initial analysis noise and improve the user experience for our migrating customers.

## Acceptance Criteria

When `qlty config migrate` is run on a repository containing a `.codeclimate.yml` (after `qlty init` has generated a base `qlty.toml`):

- Any `[[plugin]]` blocks for plugins which are present in the `.codeclimate.yml` are left unmodified
- Any `[[plugin]]` blocks for plugins which are _not_ present in the `.codeclimate.yml` file are removed entirely from the `qlty.toml` file

All other behavior of `qlty config migrate` should remain unchanged.

### Given this `.codeclimate.yml` (Input):

```yaml
# ... More config here ...
plugins:
  fixme:
    enabled: true
  csslint:
    enabled: true
  rubocop:
    enabled: true
```

And this `qlty.toml` file:

```toml
# ... More config ...

[[plugin]]
name = "shellcheck"

[[plugin]]
name = "rubocop"
```

After running `qlty config migrate`, the `qlty.toml` file should be updated as follows:

```toml
# ... More config ...

[[plugin]]
name = "rubocop"
```

The `shellcheck` plugin was removed from `qlty.toml` because it was not mentioned in `.codeclimate.yml`.
